version: '3.09'
services:
  traefic:
    image: traefik:v2.8
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.file.directory=/etc/traefik/dynamic_conf
      - --providers.file.watch=true
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs/:/certs/:ro
      - ./traefik.yml:/etc/traefik/dynamic_conf/conf.yml:ro
  node:
    build: ./
    container_name: node-server
    restart: always
    labels:
      #     # http with redirection
      - traefik.http.middlewares.redirect-middleware.redirectscheme.scheme=https
      - traefik.http.routers.web-router.entrypoints=web
      - traefik.http.routers.web-router.rule=Host(`cryptospacemap.com`)
      - traefik.http.routers.web-router.middlewares=redirect-middleware
      #     # https
      - traefik.http.routers.websecure-router.entrypoints=websecure
      - traefik.http.routers.websecure-router.tls=true
      - traefik.http.routers.websecure-router.rule=Host(`cryptospacemap.com`)